kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: config-reader-book
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-book
subjects:
  - kind: ServiceAccount
    name: book
    namespace: default
roleRef:
  kind: Role
  name: config-reader-book
  apiGroup: rbac.authorization.k8s.io
