apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "author.fullname" . }}
  labels:
    app: author
    application: library-apm
{{ include "author.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "author.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: author
      application: library-apm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "author.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: author
        application: library-apm
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "author.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 10000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            failureThreshold: 5
            periodSeconds: 30
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            initialDelaySeconds: 45
            failureThreshold: 5
            periodSeconds: 30
            successThreshold: 2
            timeoutSeconds: 10
            httpGet:
              path: /actuator/health
              port: http
          volumeMounts:
            - mountPath: /var/apps/log
              name: app-logs
          env:
            - name: ELASTIC_APM_ENABLE_LOG_CORRELATION
              value: "true"
            - name: JAVA_MEM_OPTS
              value: {{ .Values.memory }}
          envFrom:
            - configMapRef:
                name: author-db-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: app-logs
          emptyDir: {}
