{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "author.serviceAccountName" . }}
  labels:
{{ include "author.labels" . | indent 4 }}
{{- end -}}
