apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tiller-clusterrole
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - extensions
    resources:
      - thirdpartyresources
    verbs:
      - "*"
  - apiGroups:
      - ""
      - "apps"
      - "extensions"
    resources: [ "*" ]
    verbs: [ "*" ]
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - replicasets
      - daemonsets
    verbs: [ "create", "get", "list", "watch", "patch" ]
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs: [ "get", "list", "watch", "create", "delete", "patch" ]
  - apiGroups:
      - extensions
    resources:
      - replicasets
      - daemonsets
    verbs: [ "get", "list", "watch", "patch" ]
  - apiGroups: [ "" ]
    resources:
      - namespaces
      - replicationcontrollers
    verbs: [ "get", "list", "watch", "patch" ]
  - apiGroups: [ "" ]
    resources:
      - configmaps
    verbs: [ "create", "update", "get", "delete" ]
  - apiGroups: [ "" ]
    resources:
      - secrets
    verbs: [ "get" ]
  - apiGroups: [ "" ]
    resources:
      - events
    verbs: [ "create" ]
  - apiGroups: [ "" ]
    resources:
      - nodes
    verbs: [ "list" ]
  - apiGroups: [ "" ]
    resources:
      - pods
    verbs: [ "get", "create", "list", "delete", "deletecollection" ]
  - apiGroups: [ "" ]
    resources:
      - serviceaccounts
    verbs: [ "get", "create", "patch", "delete" ]
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs: [ "get", "create", "delete", "patch" ]
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: [ "get", "create", "delete", "patch" ]
  - nonResourceURLs: [ "/metrics" ]
    verbs: [ "get", "list" ]
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes/stats
      - nodes/metrics
    verbs:
      - get
  - apiGroups:
      - policy
      - apps
    resources:
      - poddisruptionbudgets
      - deployments
    verbs:
      - "*"
