apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: packetbeat
  labels:
    app: es-cluster
    tier: apm
spec:
  selector:
    matchLabels:
      app: es-cluster
      tier: apm
  template:
    metadata:
      labels:
        app: es-cluster
        tier: apm
    spec:
      serviceAccountName: packetbeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: packetbeat
          image: docker.elastic.co/beats/packetbeat:7.4.2
          imagePullPolicy: Always
          args: [
            "-c", "/etc/packetbeat.yml",
            "-e",
          ]
          securityContext:
            runAsUser: 0
            privileged: true
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
                - NET_RAW
                - NET_ADMIN
                - SYS_PTRACE
                - DAC_READ_SEARCH
          volumeMounts:
            - name: config
              mountPath: /etc/packetbeat.yml
              readOnly: true
              subPath: packetbeat.yml
            - name: data
              mountPath: /usr/share/packetbeat/data
            - name: dockersock
              mountPath: /var/run/docker.sock
            - name: proc
              mountPath: /hostfs/proc
              readOnly: true
            - name: cgroup
              mountPath: /hostfs/sys/fs/cgroup
              readOnly: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
        - name: config
          configMap:
            defaultMode: 0600
            name: packetbeat-config
        - name: data
          emptyDir: {}
        - name: proc
          hostPath:
            path: /proc
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
