apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    app: gateway
    application: library-apm
{{ include "gateway.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: gateway
    application: library-apm
